
spring.datasource.url=jdbc:mysql://localhost:3306/spms_empdb
spring.datasource.username=root
spring.datasource.password=div123


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8082

emp.message=good morning
